[[language]]
name = "typescript"
language-servers = [ "deno" ]
auto-format = true
formatter = {command = "deno", args = ["fmt", "-"]}

[language-server.deno]
command = "deno"
args = ["lsp"]
config = { enable = true, lint = true, unstable = true }

